# Generated by Django 4.2.3 on 2023-08-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_rare_cost_artifact_rage_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='rarity',
            new_name='quality',
        ),
    ]
