# Generated by Django 4.2.3 on 2023-08-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='img_full',
        ),
        migrations.AddField(
            model_name='guide',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
