# Generated by Django 4.2.3 on 2023-08-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_guide_img_full_guide_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='main_stats_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='artifact',
            name='main_stats_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='artifact',
            name='secondary_stats_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='artifact',
            name='secondary_stats_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guide',
            name='img_preview',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
